### ISSUE TITLE
Get a selection of MakerSpaces

### ISSUE THREAD

**Issue by jesp209i** [julian-code/makersofdenmark#15]
## SubTask
- Start by showing all MakerSpaces
- (Later) Search function

## Danish Name
Vis et udsnit af MakerSpaces (søge funktion) 
- Start med at vise alle
- (senere) Søgefunktion

**Comment by jesp209i** [comment]
# Request
- [GET]
- /api/makerspace

- /api/makerspace?query=hest

# Response
- 200
```
[
 {
   id: (guid),
   name: (string),
   Address: (string),
   LogoUrl: (string),
   MakerSpaceType: (string),
   AccessType: (string)
 },
 {
  ...
 }
]
```

**Comment by mnabe** [comment]
Parametre arrangeres som queryStrings
