### ISSUE TITLE
Show MakerSpace Page

### ISSUE THREAD

**Issue by jesp209i** [julian-code/makersofdenmark#16]
## Sub Task
Include Machines / options

## Danish Name
Vis MakerSpace
- Inklusive maskiner/muligheder

**Comment by julian-code** [comment]
Skal dette forståes som en Get? @jesp209i

**Comment by julian-code** [comment]
Skal dette forståes som en Get? I så fald vil endpointet nok være noget ala. /api/MakerSpace?id={Guid}.

Strukturen ville nok se således ud:
MakerSpace:
{
  "id": "00000000-0000-0000-0000-000000000000",
  "address": "",
  "organization": "",
  "tools": []
}
Tool:
{
  "name": "",
  "category": ""
}
@jesp209i

**Comment by julian-code** [comment]
Dette er mundet ud i to endpoints:
[GET] /api/makerspace/{guid}
Response:
```
{
  "address": "",
  "organization": "",
  "accessType": "",
  "contactInfo: ["","",""]
  "logoUrl": "www.google.com/"
  "vatNumber: "",
  "makerSpaceType": "",
  "accessType": ""
}
```
```
[GET] /api/makerspace/{guid}/tool
{
[
{ "name": "", "categories": [{"name": ""}]}
]
}
