### ISSUE TITLE
Fejl i produktion

### ISSUE THREAD

**Issue by julian-code** [julian-code/makersofdenmark#54]
Vi har pt. en fejl i produktion, som gør at siden er nede.

Her ses fra IIS eventloggen hvad fejlen er:

<Data>Category: Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer EventId: 2 Connection ID "17077649792894502377", Request ID "(null)": An unhandled exception was thrown by the application. Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. File name: 'System.Runtime.CompilerServices.Unsafe, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' at Microsoft.Extensions.Primitives.StringValues.IsNullOrEmpty(StringValues value) at Microsoft.AspNetCore.Hosting.HostingApplicationDiagnostics.StartActivity(HttpContext httpContext, Boolean& hasDiagnosticListener) at Microsoft.AspNetCore.Hosting.HostingApplication.CreateContext(IFeatureCollection contextFeatures) at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync() </Data>

Vi skal have fundet ud af hvorfor System.Runtime.CompilerServices.Unsafe, Version=5.0.0.0 ikke kan findes.

**Comment by mnabe** [comment]
Kan der være et problem med, at version 5.0 på EntityFrameworkCore.SqlServer (som System.Runtime.CompilerServices.Unsafe, ser ud til at høre til) er et pre-lease, og at vi skal downgrade til sidste stabile release, som er version 3.1.9 af .SqlServer? Det ville dog være mærkeligt, siden vi det har virket i et stykke tid.
